@startuml
!include <C4/C4_Container>

title Container Diagram: Экосистема "WarmHouse"

Person(Пользователь, "Пользователь", "Житель посёлка\nУправляет устройствами\nНастраивает сценарии")
Person(Партнёр, "Производитель устройств", "Интеграция оборудования\nПоддержка протоколов")

System_Ext(Партнёрские_устройства, "Устройства партнёров", "Стандартные протоколы")

Container(Веб_портал, "Веб-портал", "JavaScript", "Управление\nАналитика")

System_Boundary(backend, "Бэкенд-сервисы") {
    Container(API_шлюз, "API Gateway", "Kong/Nginx", "Единая точка входа\nАутентификация\nМаршрутизация")

    ContainerDb(Устройства_данные, "Telemetry DB", "PostgreSQL", "Телеметрия")
    ContainerDb(Пользовательские_данные, "User DB", "PostgreSQL", "Данные пользователей\nПерсональные настройки")
    ContainerDb(Конфигурации, "Config DB", "Redis", "Конфигурации устройств")

    Container(Сервис_отопления, "Сервис отопления", "Go", "Управление термостатами")
    Container(Сервис_освещения, "Сервис освещения", "Go", "Контроль света")
    Container(Сервис_безопасности, "Сервис безопасности", "Go", "Камеры слежения")
    Container(Сервис_ворот, "Сервис ворот", "Go", "Контроль ворот")
    Container(Сервис_устройств, "Сервис устройств", "Go", "Регистрация устройств\nТрансляция протоколов создателей устройств")
}

Rel(Пользователь, Веб_портал, "Конфигурирует сценарии", "HTTPS")

Rel(Веб_портал, API_шлюз, "API запросы", "HTTPS")
Rel(API_шлюз, Сервис_освещения, "Управление светом", "gRPC")
Rel(API_шлюз, Сервис_безопасности, "Запросы безопасности", "gRPC")
Rel(API_шлюз, Сервис_ворот, "Контроль доступа", "gRPC")
Rel(API_шлюз, Сервис_отопления, "Команды управления", "gRPC")
Rel(API_шлюз, Сервис_устройств, "Регистрация/статус", "gRPC")


Rel(Сервис_устройств, Партнёрские_устройства, "Обмен данными")
Rel(Партнёр, Сервис_устройств, "Регистрация устройств", "HTTPS/REST")

Rel(API_шлюз, Пользовательские_данные, "Аутентификация", "SQL")
Rel(Сервис_устройств, Конфигурации, "Чтение/запись конфигов", "Redis Protocol")

Rel(Сервис_отопления, Устройства_данные, "Tелеметрия")
Rel(Сервис_безопасности, Устройства_данные, "Tелеметрия")
Rel(Сервис_ворот, Устройства_данные, "Tелеметрия")
Rel(Сервис_отопления, Устройства_данные, "Tелеметрия")
Rel(Сервис_освещения, Устройства_данные, "Tелеметрия")


@enduml
